// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/ca-nambara-teruaki/sample-app/ent/schema"
	"github.com/ca-nambara-teruaki/sample-app/ent/task"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescTitle is the schema descriptor for title field.
	taskDescTitle := taskFields[1].Descriptor()
	// task.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	task.TitleValidator = taskDescTitle.Validators[0].(func(string) error)
	// taskDescIsDeleted is the schema descriptor for is_deleted field.
	taskDescIsDeleted := taskFields[4].Descriptor()
	// task.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	task.DefaultIsDeleted = taskDescIsDeleted.Default.(bool)
}
